from django.urls import include, path, re_path
from django.conf import settings
from . import views
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [    
    #OUTSIDE LOGIN 
    path('', views.index, name='index'),
    path(r'login', views.loginPage, name="login"),
    re_path(r'logout', views.logout_view, name="logout"),
    path('about_us', views.aboutUs, name='aboutUs'),
    path('services', views.services1, name='services'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('reports', views.render_pdf_view, name='reports'),
    path('just', views.justtry, name='just'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="forgot_pass_1.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="forgot_pass_2.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="forgot_pass_3.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="forgot_pass_4.html"), name='password_reset_complete'),

    #PETOWNER
    path(r'petOwnerHome', views.petOwnerHome, name="petOwnerHome"),
    path(r'petOwnerDashBoard', views.petOwnerDashBoard, name="petOwnerDashBoard"),
    path(r'petOwnerDashBoard_one', views.petOwnerDashBoard_one, name="petOwnerDashBoard_one"),
    path('OwnerChangePass', views.OwnerChangePass, name="OwnerChangePass"),
    re_path(r'^edit_owner_profile/(?P<pk>[a-zA-Z0-9]+$)', views.edit_owner_profile, name='edit_owner_profile'),
    path('services_petOwner', views.services_petOwner, name='services_petOwner'),
    re_path(r'^view_pet_history/(?P<pk>[a-zA-Z0-9]+$)', views.view_pet_history, name='view_pet_history'),
    re_path(r'^owner_view_per_record/(?P<pk>[a-zA-Z0-9]+$)', views.owner_view_per_record, name='owner_view_per_record'),
    path('petowner_transaction_history', views.petowner_transaction_history, name='petowner_transaction_history'),
    re_path(r'^owner_view_transaction/(?P<pk>[a-zA-Z0-9]+$)', views.owner_view_transaction, name='owner_view_transaction'),
    path('choose_pet', views.choose_pet, name='choose_pet'),
    re_path(r'^scheduling/(?P<pk>[a-zA-Z0-9]+$)', views.schedulings, name='scheduling'),
    #schediling

    path('scheduling_terms_condition', views.scheduling_terms_condition, name='scheduling_terms_condition'),
    
    
    path('ajax/load-slot/', views.load_slot, name='ajax_load_slot'),
    path('upcomming_app/', views.upcomming_app, name='upcomming_app'),
    path('cancelled_appointments/', views.cancelled_appointments, name='cancelled_appointments'),
    re_path(r'^edit_pet_pfp/(?P<pk>[a-zA-Z0-9]+$)', views.edit_pet_pfp, name='edit_pet_pfp'),

    #HEADVET
    path(r'headVetHome', views.headVetHome, name="headVetHome"),
    path('headvetChangePass', views.headvetChangePass, name="headvetChangePass"),
    path(r'headvetDashBoard', views.headvetDashboard, name="headvetDashBoard"),
    path(r'headvetDashBoard_one', views.headvetDashboard_one, name="headvetDashBoard_one"),
    re_path(r'^headdone/(?P<pk>[a-zA-Z0-9]+$)', views.headdone_pet, name='headdone'),
    path('headvet_upcoming_app/', views.headvet_upcoming_app, name='headvet_upcoming_app'),
    re_path(r'^edit_headvet_profile/(?P<pk>[a-zA-Z0-9]+$)', views.edit_headvet_profile, name='edit_headvet_profile'),
    path('head_patientsTab', views.head_patientsTab, name='head_patientsTab'),
    re_path(r'^head_create_pet_record/(?P<pk>[a-zA-Z0-9]+$)', views.head_create_pet_record, name='head_create_pet_record'),
    re_path(r'^head_view_record/(?P<pk>[a-zA-Z0-9]+$)', views.head_view_record, name='head_view_record'),
    re_path(r'^head_view_per_record/(?P<pk>[a-zA-Z0-9]+$)', views.head_view_per_record, name='head_view_per_record'),
    re_path(r'^head_vet_add_medical_service/(?P<pk>[a-zA-Z0-9]+$)', views.head_vet_add_medical_service, name='head_vet_add_medical_service'),
    re_path(r'^head_vet_availed_service/(?P<pk>[a-zA-Z0-9]+$)', views.head_vet_availed_service, name='head_vet_availed_service'),
    re_path(r'^head_vet_availed_labTest/(?P<pk>[a-zA-Z0-9]+$)', views.head_vet_availed_labTest, name='head_vet_availed_labTest'),
    re_path(r'^head_vet_availed_vaccination/(?P<pk>[a-zA-Z0-9]+$)', views.head_vet_availed_vaccination, name='head_vet_availed_vaccination'),
    re_path(r'^head_vet_edit_availed_service/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_edit_availed_service, name='head_vet_edit_availed_service'),
    re_path(r'^head_vet_edit_lab_test/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_edit_lab_test, name='head_vet_edit_lab_test'),
    re_path(r'^head_vet_edit_vaccination/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_edit_vaccination, name='head_vet_edit_vaccination'),
    re_path(r'^head_vet_update_medical_history/(?P<pk>[a-zA-Z0-9]+$)', views.head_vet_update_medical_history, name='head_vet_update_medical_history'),  
    re_path(r'^head_vet_delete_availed_service/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_delete_availed_service, name='head_vet_delete_availed_service'),   
    re_path(r'^head_vet_delete_availed_lab/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_delete_availed_lab, name='head_vet_delete_availed_lab'),  
    re_path(r'^head_vet_delete_availed_vaccine/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_delete_availed_vaccine, name='head_vet_delete_availed_vaccine'),     
    path('head_vet_add_pets', views.head_vet_pet_create_view, name='head_vet_pet_add'),
    re_path(r'^head_generateServiceInvoice/(?P<pk2>[a-zA-Z0-9]+$)', views.headvet_generateServiceInvoice, name='head_serviceInvoice'),
    re_path(r'^head_modify_product/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.headvet_modify_quantity, name='head_modify_product'),
    re_path(r'^head_vet_remove_product/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.head_vet_remove_product, name='head_vet_remove_product'),
    path('head_service_reports/', views.head_service_reports, name='head_service_reports'),
    path('head_today_service_reports/', views.head_today_service_reports, name='head_today_service_reports'),
    path('head_last_seven_service_reports/', views.head_seven_service_reports, name='head_last_seven_service_reports'),
    path('head_last_thirty_service_reports/', views.head_last_thirty_service_reports, name='head_last_thirty_service_reports'),
    path('head_a_year_ago_service_reports/', views.head_a_year_ago_service_reports, name='head_a_year_ago_service_reports'),
    path('head_more_service_reports/', views.head_more_service_reports, name='head_more_service_reports'),
    path('head_product_reports/', views.head_product_reports, name='head_product_reports'),
    path('head_today_product_reports/', views.head_today_product_reports, name='head_today_product_reports'),
    path('head_last_seven_product_reports/', views.head_seven_product_reports, name='head_last_seven_product_reports'),
    path('head_last_thirty_product_reports/', views.head_last_thirty_product_reports, name='head_last_thirty_product_reports'),
    path('head_a_year_ago_product_reports/', views.head_a_year_ago_product_reports, name='head_a_year_ago_product_reports'),
    path('head_more_product_reports/', views.head_more_product_reports, name='head_more_product_reports'), 
    path(r'head_transaction_reports', views.head_transaction_reports, name="head_transaction_reports"),
    re_path(r'^head_transaction_reports_select/(?P<pk>[a-zA-Z0-9]+$)', views.head_transaction_reports_select, name='head_transaction_reports_select'),

    #VETERINARIAN
    path(r'veterinarianHome', views.veterinarianHome, name="veterinarianHome"),
    path('vetChangePass', views.vetChangePass, name="vetChangePass"),
    path(r'vetDashBoard', views.vetDashboard, name="vetDashBoard"),
    path(r'vetDashBoard_one', views.vetDashboard_one, name="vetDashBoard_one"),
    re_path(r'^done/(?P<pk>[a-zA-Z0-9]+$)', views.done_pet, name='done'),
    re_path(r'^edit_vet_profile/(?P<pk>[a-zA-Z0-9]+$)', views.edit_vet_profile, name='edit_vet_profile'),
    path('services_veterinarian', views.services_veterinarian, name='services_veterinarian'),
    re_path(r'^create_pet_record/(?P<pk>[a-zA-Z0-9]+$)', views.create_pet_record, name='create_pet_record'),
    re_path(r'^view_record/(?P<pk>[a-zA-Z0-9]+$)', views.view_record, name='view_record'),
    re_path(r'^view_per_record/(?P<pk>[a-zA-Z0-9]+$)', views.view_per_record, name='view_per_record'),
    re_path(r'^vet_add_medical_service/(?P<pk>[a-zA-Z0-9]+$)', views.vet_add_medical_service, name='vet_add_medical_service'),
    re_path(r'^vet_availed_service/(?P<pk>[a-zA-Z0-9]+$)', views.vet_availed_service, name='vet_availed_service'),
    re_path(r'^vet_availed_labTest/(?P<pk>[a-zA-Z0-9]+$)', views.vet_availed_labTest, name='vet_availed_labTest'),
    re_path(r'^vet_availed_vaccination/(?P<pk>[a-zA-Z0-9]+$)', views.vet_availed_vaccination, name='vet_availed_vaccination'),
    re_path(r'^vet_edit_availed_service/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_edit_availed_service, name='vet_edit_availed_service'),
    re_path(r'^vet_edit_lab_test/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_edit_lab_test, name='vet_edit_lab_test'),
    re_path(r'^vet_edit_vaccination/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_edit_vaccination, name='vet_edit_vaccination'),
    re_path(r'^vet_update_medical_history/(?P<pk>[a-zA-Z0-9]+$)', views.vet_update_medical_history, name='vet_update_medical_history'),    
    re_path(r'^vet_delete_availed_service/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_delete_availed_service, name='vet_delete_availed_service'),   
    re_path(r'^vet_delete_availed_lab/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_delete_availed_lab, name='vet_delete_availed_lab'),  
    re_path(r'^vet_delete_availed_vaccine/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_delete_availed_vaccine, name='vet_delete_availed_vaccine'),   
    path('vet_add_pets', views.vet_pet_create_view, name='vet_pet_add'),
    re_path(r'^generateServiceInvoice/(?P<pk2>[a-zA-Z0-9]+$)', views.generateServiceInvoice, name='serviceInvoice'),
    re_path(r'^modify_product/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.modify_quantity, name='modify_product'),
    re_path(r'^vet_remove_product/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.vet_remove_product, name='vet_remove_product'),
    #Vet Schedule
    path('vet_upcoming_app/', views.vet_upcoming_app, name='vet_upcoming_app'),
    
    #SECRETARY
    path(r'secDashBoard', views.secretaryDashboard, name="secDashBoard"),
    path('SecChangePass', views.SecChangePass, name="SecChangePass"),
    path(r'secDashBoard_one', views.secretaryDashboard_one, name="secDashBoard_one"),
    path(r'secDashBoard_low', views.secretaryDashboard_low, name="secDashBoard_low"),
    path(r'secDashBoard_no', views.secretaryDashboard_no, name="secDashBoard_no"),
    path(r'secretaryHome', views.secretaryHome, name="secretaryHome"),
    re_path(r'^edit_sec_profile/(?P<pk>[a-zA-Z0-9]+$)', views.edit_sec_profile, name='edit_sec_profile'),
    path('products_secretary', views.products_secretary, name='products_secretary'),
    #Sec ChargeSlip
    path('billing', views.sec_chargeslip, name='billing'),
    path('fully_billing', views.sec_chargeslip_fully, name='fully_billing'),
    path('partial_billing', views.sec_chargeslip_partial, name='partial_billing'),
    path('unpaid_billing', views.sec_chargeslip_unpaid, name='unpaid_billing'),
    path('sec_transaction', views.sec_transaction, name='sec_transaction'),
    re_path(r'^transaction_view/(?P<pk>[a-zA-Z0-9]+$)', views.transaction_view, name='transaction_view'),
    re_path(r'^chargeslip_edit/(?P<pk>[a-zA-Z0-9]+$)', views.chargeSlip_edit, name='chargeslip_edit'),
    re_path(r'^sec_modify_product/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.sec_modify_quantity, name='sec_modify_product'),  
    re_path(r'^sec_remove_product/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.sec_remove_product, name='sec_remove_product'),
    re_path(r'^chargeslip_view/(?P<pk>[a-zA-Z0-9]+$)', views.chargeslipView, name='chargeslip_view'),
    re_path(r'^transact_payment/(?P<pk>[a-zA-Z0-9]+$)', views.transact_payment, name='transact_payment'),
    re_path(r'^sec_remove_outside/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.sec_remove_outside, name='sec_remove_outside'),
    re_path(r'^sec_modify_outside/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.sec_modify_outside, name='sec_modify_outside'),
    path('outside_buyer', views.outside_buyer, name='outside_buyer'),
    re_path(r'^outside_buyer_created/(?P<pk>[a-zA-Z0-9]+$)', views.outside_buyer_created, name='outside_buyer_edit'),
    re_path(r'^cancelled_app/(?P<pk>[a-zA-Z0-9]+$)', views.cancelled_app, name='cancelled_app'),
    #Sec Schedule Slot
    path('scheduling_slot', views.set_appointment_slot, name='scheduling_slot'),
    re_path(r'^edit_scheduling_slot/(?P<pk>[a-zA-Z0-9]+$)', views.edit_set_appointment_slot, name='edit_scheduling_slot'),
    re_path(r'^delete_scheduling_slot/(?P<pk>[a-zA-Z0-9]+$)', views.delete_scheduling_slot, name='delete_scheduling_slot'),
    path('sec_upcoming_app/', views.sec_set_of_appointments, name='sec_upcoming_app'),
    re_path(r'^arrived/(?P<pk>[a-zA-Z0-9]+$)', views.arrived_pet, name='arrived'),
    re_path(r'^didnotarrived/(?P<pk>[a-zA-Z0-9]+$)', views.didnotarrived, name='didnotarrived'),
        re_path(r'^setarrived/(?P<pk>[a-zA-Z0-9]+$)', views.setarrived_pet, name='setarrived'),
    re_path(r'^setdidnotarrived/(?P<pk>[a-zA-Z0-9]+$)', views.setdidnotarrived, name='setdidnotarrived'),
    path('restricted/', views.restricted, name='restricted'),
    re_path(r'^unsrestrict/(?P<pk>[a-zA-Z0-9]+$)', views.unsrestrict, name='unsrestrict'),

    

    #Sec medical history
    path('add_medical_service', views.add_medical_service, name='add_medical_service'),
    re_path(r'^direct_add_medical_history/(?P<pk>[a-zA-Z0-9]+$)', views.direct_add_medical_history, name='direct_add_medical_history'),
    path('add_medical_history', views.add_medical_history, name='add_medical_history'),
    re_path(r'^update_medical_history/(?P<pk>[a-zA-Z0-9]+$)', views.update_medical_history, name='update_medical_history'),
    re_path(r'^add_medical_service/(?P<pk>[a-zA-Z0-9]+$)', views.add_medical_service, name='add_medical_service'),
    re_path(r'^availed_service/(?P<pk>[a-zA-Z0-9]+$)', views.availed_service, name='availed_service'),
    re_path(r'^availed_labTest/(?P<pk>[a-zA-Z0-9]+$)', views.availed_labTest, name='availed_labTest'),
    re_path(r'^availed_vaccination/(?P<pk>[a-zA-Z0-9]+$)', views.availed_vaccination, name='availed_vaccination'),
    re_path(r'^view_all_medical_history/(?P<pk>[a-zA-Z0-9]+$)', views.view_all_medical_history, name='view_all_medical_history'),
    re_path(r'^view_medical_history/(?P<pk>[a-zA-Z0-9]+$)', views.view_medical_history, name='view_medical_history'),
    re_path(r'^delete_history/(?P<pk>[a-zA-Z0-9]+$)', views.delete_history, name='delete_history'),
    re_path(r'^edit_availed_service/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.edit_availed_service, name='edit_availed_service'),
    re_path(r'^edit_lab_test/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.edit_lab_test, name='edit_lab_test'),
    re_path(r'^edit_vaccination/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.edit_vaccination, name='edit_vaccination'),
    re_path(r'^delete_availed_service/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.delete_availed_service, name='delete_availed_service'),   
    re_path(r'^delete_availed_lab/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.delete_availed_lab, name='delete_availed_lab'),  
    re_path(r'^delete_availed_vaccine/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.delete_availed_vaccine, name='delete_availed_vaccine'),   

    #Sec create
    path('add_dropdown_details', views.add_dropdown_details, name='add_dropdown_details'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('pet_record', views.pet_record, name='pet_record'),
    path('create_accounts', views.create_accounts, name='create_accounts'),
    path('add_users', views.add_users, name='add_users'),
    path('add_users_headvet', views.add_users_headvet, name='add_users_headvet'),
    path('add_users_vet', views.add_users_vet, name='add_users_vet'),
    path('add_users_sec', views.add_users_sec, name='add_users_sec'),
    re_path(r'^delete_user/(?P<pk>[a-zA-Z0-9]+$)', views.delete_user, name='delete_users'),
    re_path(r'^update_user/(?P<pk>[a-zA-Z0-9]+$)', views.update_user, name='update_users'),
    re_path(r'^update_profile/(?P<pk>[a-zA-Z0-9]+$)', views.update_profile, name='update_profile'),
    path('add_petowner_profile', views.add_petowner_profile, name='add_petowner_profile'),
    path('add_petowner_account', views.add_petowner_account, name='add_petowner_account'),
    re_path(r'^add_petowner_account_direct/(?P<pk>[a-zA-Z0-9]+$)', views.add_petowner_account1, name='add_petowner_account1'),
    re_path(r'^update_petowner_profile/(?P<pk>[a-zA-Z0-9]+$)', views.update_petownerprofile, name='update_petownerprofile'),
    re_path(r'^direct_add_users/(?P<pk>[a-zA-Z0-9]+$)', views.direct_add_users, name='direct_add_users'),
    re_path(r'^delete_profile/(?P<pk>[a-zA-Z0-9]+$)', views.delete_profile, name='delete_profile'),
    path('add_veterinarian_profile', views.add_veterinarian_profile, name='add_veterinarian_profile'),
    path('add_veterinarian_account', views.add_veterinarian_account, name='add_veterinarian_account'),
    re_path(r'^update_vet_profile/(?P<pk>[a-zA-Z0-9]+$)', views.update_vet_profile, name='update_vet_profile'),
    re_path(r'^direct_add_users_vet/(?P<pk>[a-zA-Z0-9]+$)', views.direct_add_users_vet, name='direct_add_users_vet'),
    re_path(r'^delete_vet_profile/(?P<pk>[a-zA-Z0-9]+$)', views.delete_vet_profile, name='delete_vet_profile'),
    path('add_headveterinarian_profile', views.add_headveterinarian_profile, name='add_headveterinarian_profile'),
    path('add_headveterinarian_account', views.add_headveterinarian_account, name='add_headveterinarian_account'),
    re_path(r'^update_headvet_profile/(?P<pk>[a-zA-Z0-9]+$)', views.update_headvet_profile, name='update_headvet_profile'),
    re_path(r'^direct_add_users_headvet/(?P<pk>[a-zA-Z0-9]+$)', views.direct_add_users_headvet, name='direct_add_users_headvet'),
    path('add_sec_profile', views.add_sec_profile, name='add_sec_profile'),
    path('add_sec_account', views.add_sec_account, name='add_sec_account'),
    re_path(r'^update_sec_profile/(?P<pk>[a-zA-Z0-9]+$)', views.update_sec_profile, name='update_sec_profile'),
    re_path(r'^direct_add_users_sec/(?P<pk>[a-zA-Z0-9]+$)', views.direct_add_users_sec, name='direct_add_users_sec'),
    re_path(r'^delete_sec_profile/(?P<pk>[a-zA-Z0-9]+$)', views.delete_sec_profile, name='delete_sec_profile'),
    path('add_species', views.add_species, name='add_species'),
    re_path(r'^update_species/(?P<pk>[a-zA-Z0-9]+$)', views.update_species, name='update_species'),
    re_path(r'^delete_species/(?P<pk>[a-zA-Z0-9]+$)', views.delete_species, name='delete_species'),
    path('add_vaccineType', views.add_vaccineType, name='add_vaccineType'),
    re_path(r'^update_vaccineType/(?P<pk>[a-zA-Z0-9]+$)', views.update_vaccineType, name='update_vaccineType'),
    re_path(r'^delete_vaccineType/(?P<pk>[a-zA-Z0-9]+$)', views.delete_vaccineType, name='delete_vaccineType'),
    re_path(r'^delete_pets/(?P<pk>[a-zA-Z0-9]+$)', views.delete_pets, name='delete_pets'),
    path('add_services', views.add_service, name='add_services'),
    re_path(r'^update_services/(?P<pk>[a-zA-Z0-9]+$)', views.update_service, name='update_services'),
    re_path(r'^delete_services/(?P<pk>[a-zA-Z0-9]+$)', views.delete_service, name='delete_services'),
    path('add_productType', views.add_prodType, name='add_productType'),
    re_path(r'^update_productType/(?P<pk>[a-zA-Z0-9]+$)', views.update_prodType, name='update_productType'),
    re_path(r'^delete_productType/(?P<pk>[a-zA-Z0-9]+$)', views.delete_prodType, name='delete_productType'),
    path('add_breed', views.add_breeds, name='add_breed'),
    re_path(r'^update_breeds/(?P<pk>[a-zA-Z0-9]+$)', views.update_breeds, name='breed_change'),
    re_path(r'^delete_breeds/(?P<pk>[a-zA-Z0-9]+$)', views.delete_breeds, name='delete_breed'),
    path('products/', views.products, name='products'),
    path('add_product/', views.addProduct, name="add_product"),
    re_path(r'^update_product/(?P<pk>[a-zA-Z0-9]+$)', views.updateProduct, name='update_product'),
    re_path(r'^delete_product/(?P<pk>[a-zA-Z0-9]+$)', views.deleteProduct, name='delete_product'),
    re_path(r'^available_products/(?P<pk>[a-zA-Z0-9]+$)', views.productsInventory, name="available_products"),
    re_path(r'^add_available_products/(?P<pk>[a-zA-Z0-9]+$)', views.addproductsInventory, name="add_available_products"),
    re_path(r'^update_available_products/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.updateproductsInventory, name="update_available_products"),
    re_path(r'^delete_available_products/(?P<pk>[a-zA-Z0-9]+)/(?P<pk2>[a-zA-Z0-9]+$)', views.deleteproductsInventory, name="delete_available_products"), 
    path('add_gender/', views.add_gender, name="add_gender"),
    re_path(r'^update_gender/(?P<pk>[a-zA-Z0-9]+$)', views.update_gender, name='update_gender'),
    re_path(r'^delete_gender/(?P<pk>[a-zA-Z0-9]+$)', views.delete_gender, name='delete_gender'),
    path('add_pets', views.pet_create_view, name='pet_add'),
    re_path(r'^updatepets/(?P<pk>[a-zA-Z0-9]+$)', views.pet_update_view, name='pet_change'),
    re_path(r'^add_pets_owner/(?P<pk>[a-zA-Z0-9]+$)', views.pet_create_view_per_owner, name='pet_add_in_owner'),
    path('ajax/load-cities/', views.load_breed, name='ajax_load_cities'),
    path('archive_pets', views.archive_pets, name='archive_pets'),
   
    #archive
    path('recovery', views.recover, name='recovery'),
    path('archive_accounts', views.archive_accounts, name='archive_accounts'),
    re_path(r'^recover_user/(?P<pk>[a-zA-Z0-9]+$)', views.recover_user, name='recover_user'),
    path('archive_pets', views.archive_pets, name='archive_pets'),
    re_path(r'^recover_pets/(?P<pk>[a-zA-Z0-9]+$)', views.recover_pet, name='recover_pets'),
    path('archive_medHistory', views.archive_medHistory, name='archive_medHistory'),
    re_path(r'^recover_history/(?P<pk>[a-zA-Z0-9]+$)', views.recover_history, name='recover_history'),

    #reports
    path(r'transaction_reports', views.transaction_reports, name="transaction_reports"),
    re_path(r'^transaction_reports_select/(?P<pk>[a-zA-Z0-9]+$)', views.transaction_reports_select, name='transaction_reports_select'),
    path('service_reports/', views.service_reports, name='service_reports'),
    path('today_service_reports/', views.today_service_reports, name='today_service_reports'),
    path('last_seven_service_reports/', views.seven_service_reports, name='last_seven_service_reports'),
    path('last_thirty_service_reports/', views.last_thirty_service_reports, name='last_thirty_service_reports'),
    path('a_year_ago_service_reports/', views.a_year_ago_service_reports, name='a_year_ago_service_reports'),
    path('more_service_reports/', views.more_service_reports, name='more_service_reports'),
    path('product_reports/', views.product_reports, name='product_reports'),
    path('today_product_reports/', views.today_product_reports, name='today_product_reports'),
    path('last_seven_product_reports/', views.seven_product_reports, name='last_seven_product_reports'),
    path('last_thirty_product_reports/', views.last_thirty_product_reports, name='last_thirty_product_reports'),
    path('a_year_ago_product_reports/', views.a_year_ago_product_reports, name='a_year_ago_product_reports'),
    path('more_product_reports/', views.more_product_reports, name='more_product_reports'), 
    path('chargeSlip_reports/', views.chargeSlip_reports, name='chargeSlip_reports'),
    path('today_chargeSlip_reports/', views.today_chargeSlip_reports, name='today_chargeSlip_reports'),
    path('last_seven_chargeSlip_reports/', views.seven_chargeSlip_reports, name='last_seven_chargeSlip_reports'),
    path('last_thirty_chargeSlip_reports/', views.last_thirty_chargeSlip_reports, name='last_thirty_chargeSlip_reports'),
    path('a_year_ago_chargeSlip_reports/', views.a_year_ago_chargeSlip_reports, name='a_year_ago_chargeSlip_reports'),
    path('more_chargeSlip_reports/', views.more_chargeSlip_reports, name='more_chargeSlip_reports'), 
    path('fully_chargeSlip_reports/', views.fully_chargeSlip_reports, name='fully_chargeSlip_reports'),
    path('fully_today_chargeSlip_reports/', views.fully_today_chargeSlip_reports, name='fully_today_chargeSlip_reports'),
    path('fully_last_seven_chargeSlip_reports/', views.fully_seven_chargeSlip_reports, name='fully_last_seven_chargeSlip_reports'),
    path('fully_last_thirty_chargeSlip_reports/', views.fully_last_thirty_chargeSlip_reports, name='fully_last_thirty_chargeSlip_reports'),
    path('fully_a_year_ago_chargeSlip_reports/', views.fully_a_year_ago_chargeSlip_reports, name='fully_a_year_ago_chargeSlip_reports'),
    path('fully_more_chargeSlip_reports/', views.fully_more_chargeSlip_reports, name='fully_more_chargeSlip_reports'), 
    path('Unpaid_chargeSlip_reports/', views.Unpaid_chargeSlip_reports, name='Unpaid_chargeSlip_reports'),
    path('Unpaid_today_chargeSlip_reports/', views.Unpaid_today_chargeSlip_reports, name='Unpaid_today_chargeSlip_reports'),
    path('Unpaid_last_seven_chargeSlip_reports/', views.Unpaid_seven_chargeSlip_reports, name='Unpaid_last_seven_chargeSlip_reports'),
    path('last_thirty_chargeSlip_reports/', views.Unpaid_last_thirty_chargeSlip_reports, name='Unpaid_last_thirty_chargeSlip_reports'),
    path('Unpaid_a_year_ago_chargeSlip_reports/', views.Unpaid_a_year_ago_chargeSlip_reports, name='Unpaid_a_year_ago_chargeSlip_reports'),
    path('Unpaid_more_chargeSlip_reports/', views.Unpaid_more_chargeSlip_reports, name='Unpaid_more_chargeSlip_reports'), 
    path('partial_chargeSlip_reports/', views.partial_chargeSlip_reports, name='partial_chargeSlip_reports'),
    path('partial_today_chargeSlip_reports/', views.partial_today_chargeSlip_reports, name='partial_today_chargeSlip_reports'),
    path('partial_last_seven_chargeSlip_reports/', views.partial_seven_chargeSlip_reports, name='partial_last_seven_chargeSlip_reports'),
    path('partial_last_thirty_chargeSlip_reports/', views.partial_last_thirty_chargeSlip_reports, name='partial_last_thirty_chargeSlip_reports'),
    path('partial_a_year_ago_chargeSlip_reports/', views.partial_a_year_ago_chargeSlip_reports, name='partial_a_year_ago_chargeSlip_reports'),
    path('partial_more_chargeSlip_reports/', views.partial_more_chargeSlip_reports, name='partial_more_chargeSlip_reports'), 
    path('inventory_summary/', views.inventory_summary, name='inventory_summary'), 
    path('transaction_report/', views.transaction_report, name='transaction_report'), 
    path('today_transaction_reports/', views.today_transaction_reports, name='today_transaction_reports'),
    path('last_seven_transaction_reports/', views.seven_transaction_reports, name='last_seven_transaction_reports'),
    path('last_thirty_transaction_reports/', views.last_thirty_transaction_reports, name='last_thirty_transaction_reports'),
    path('a_year_ago_transaction_reports/', views.a_year_ago_transaction_reports, name='a_year_ago_transaction_reports'),
    path('more_transaction_reports/', views.more_transaction_reports, name='more_transaction_reports'), 
    path('all_products_reports/', views.all_products_reports, name='all_products_reports'), 
    re_path(r'^single_product_reports/(?P<pk>[a-zA-Z0-9]+$)', views.single_product_reports, name='single_product_reports'),
    path('client_reports/', views.client_reports, name='client_reports'),
    path('client_report/', views.client_report, name='client_report'),
    path('today_client_reports/', views.today_client_reports, name='today_client_reports'),
    path('last_seven_client_reports/', views.seven_client_reports, name='last_seven_client_reports'),
    path('last_thirty_client_reports/', views.last_thirty_client_reports, name='last_thirty_client_reports'),
    path('a_year_ago_client_reports/', views.a_year_ago_client_reports, name='a_year_ago_client_reports'),
    path('more_client_reports/', views.more_client_reports, name='more_client_reports'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

