# Generated by Django 4.0.6 on 2022-07-06 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_inactive', models.DateTimeField(blank=True, null=True, verbose_name='Date of Inacitve')),
                ('is_used', models.BooleanField(default=False)),
                ('is_secretary', models.BooleanField(default=False, verbose_name='Secretary')),
                ('is_headveterinarian', models.BooleanField(default=False, verbose_name='Head Veterinarian')),
                ('is_veterinarian', models.BooleanField(default=False, verbose_name='Veterinarian')),
                ('is_petowner', models.BooleanField(default=False, verbose_name='Pet Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50, null=True, unique=True, verbose_name='Species')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
            ],
            options={
                'verbose_name_plural': 'Breed',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Gender')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='petspecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50, null=True, unique=True, verbose_name='Species')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
            ],
            options={
                'verbose_name_plural': 'Pet Species',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodType', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Vaccine Type')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
            ],
            options={
                'verbose_name_plural': 'Product Type',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Service')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('is_labTest', models.BooleanField(default=False, verbose_name='Laboratory Test')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='vaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccineType', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Vaccine Type')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
            ],
            options={
                'verbose_name_plural': 'Vaccine Type',
            },
        ),
        migrations.CreateModel(
            name='VeterinarianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contactNum', models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Contact must be entered in format: 09XXXXXXXXX', regex='^09\\d{9}$')], verbose_name='Contact Number')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.gender', verbose_name='Gender')),
                ('useracc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name_plural': 'Veterinarian Profile',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contactNum', models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Contact must be entered in format: 09XXXXXXXXX', regex='^09\\d{9}$')], verbose_name='Contact Number')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.gender', verbose_name='Gender')),
                ('useracc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name_plural': 'Staff Profile',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contactNum', models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Contact must be entered in format: 09XXXXXXXXX', regex='^09\\d{9}$')], verbose_name='Contact Number')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.gender', verbose_name='Gender')),
                ('useracc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name_plural': 'Pet Owner Profile',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('status', models.CharField(default='No stock', max_length=200, null=True)),
                ('total_quantity', models.IntegerField(default='0', null=True, verbose_name='Total Quantity')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='vet.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuDate', models.DateField(verbose_name='Manufacturing Date')),
                ('expireDate', models.DateField(verbose_name='Expiration Date')),
                ('quantity', models.IntegerField(default='0', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vet.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pet Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Gender')),
                ('colorMarking', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Marking')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.breed', verbose_name='Breed')),
                ('petOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.profile', verbose_name='Pet Owner')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.petspecies', verbose_name='Species')),
            ],
            options={
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.petspecies', verbose_name='Species'),
        ),
    ]
