# Generated by Django 4.0.6 on 2022-07-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VeterinarianProfile',
        ),
    ]
