# Generated by Django 4.0.6 on 2022-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_delete_veterinarianprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='low_margin',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Low Threshold'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='medium_margin',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Medium Threshold'),
        ),
    ]
