# Generated by Django 4.0.6 on 2022-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_productinfo_low_margin_productinfo_medium_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='low_margin',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='medium_margin',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
