# Generated by Django 4.0.6 on 2022-07-09 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_alter_productinfo_low_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_vaccination',
            field=models.BooleanField(default=False, verbose_name='Vaccination'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.petspecies', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.breed', verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='petOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.profile', verbose_name='Pet Owner'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.petspecies', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expireDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manuDate',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacturing Date'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vet.producttype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='useracc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='useracc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.CreateModel(
            name='serviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofService', models.DateField(verbose_name='Date of Service')),
                ('dateofResult', models.DateField(blank=True, null=True, verbose_name='Date of Service')),
                ('interpretation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Interpretation')),
                ('dateofReturn', models.DateField(blank=True, null=True, verbose_name='Date of return')),
                ('reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reason for Return')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('medHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.pets', verbose_name='Medical History')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='vet.services')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Medical Examination Date')),
                ('weight', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight')),
                ('symptoms', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Symptoms')),
                ('treatment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Treatment')),
                ('prescription', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Prescription')),
                ('instruction', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Instruction')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='vet.pets')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian')),
            ],
            options={
                'verbose_name_plural': 'Medical History',
            },
        ),
    ]
