# Generated by Django 4.0.6 on 2022-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0006_alter_servicehistory_medhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='dateofReturn',
            field=models.DateField(blank=True, null=True, verbose_name='Date of return'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reason for Return'),
        ),
    ]
