# Generated by Django 3.2 on 2022-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0007_medicalhistory_dateofreturn_medicalhistory_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'verbose_name_plural': 'Service History'},
        ),
    ]
