# Generated by Django 4.0.6 on 2022-07-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0008_alter_servicehistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='chargeSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total Amount')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Balance')),
                ('status', models.CharField(default='Unpaid', max_length=200, null=True)),
                ('petowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.profile', verbose_name='Pet Owner')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Staff')),
            ],
            options={
                'verbose_name_plural': 'Charge Slip Invoice',
            },
        ),
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'verbose_name_plural': 'General Service'},
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='dateofResult',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='dateofReturn',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='reason',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian'),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='interpretation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian'),
        ),
        migrations.CreateModel(
            name='vaccineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofService', models.DateField(verbose_name='Date of Service')),
                ('interpretation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('dateofReturn', models.DateField(blank=True, null=True, verbose_name='Date of Result')),
                ('reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('medHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.medicalhistory', verbose_name='Medical History')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.services', verbose_name='Service')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.product', verbose_name='Vaccine')),
            ],
            options={
                'verbose_name_plural': 'Vaccination History',
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of Transaction')),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total Amount')),
                ('tenderedAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Amount')),
                ('changeAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Change')),
                ('chargeslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.chargeslip', verbose_name='Charge Slip')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Staff')),
            ],
            options={
                'verbose_name_plural': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='serviceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Amount')),
                ('chargeslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.chargeslip', verbose_name='Charge Slip')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.services', verbose_name='Service')),
            ],
            options={
                'verbose_name_plural': 'Service Invoice',
            },
        ),
        migrations.CreateModel(
            name='productInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1', null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Amount')),
                ('chargeslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.chargeslip', verbose_name='Charge Slip')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Product Invoice',
            },
        ),
        migrations.CreateModel(
            name='labHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofService', models.DateField(verbose_name='Date of Service')),
                ('dateofResult', models.DateField(blank=True, null=True, verbose_name='Date of Result')),
                ('interpretation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('medHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.medicalhistory', verbose_name='Medical History')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.services', verbose_name='Service')),
            ],
            options={
                'verbose_name_plural': 'Laboratory History',
            },
        ),
    ]
