# Generated by Django 4.0.6 on 2022-07-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0009_chargeslip_alter_servicehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labhistory',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian'),
        ),
        migrations.AddField(
            model_name='vaccinehistory',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian'),
        ),
    ]
