# Generated by Django 4.0.6 on 2022-07-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0010_labhistory_vet_vaccinehistory_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='labhistory',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vaccinehistory',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productinvoice',
            name='chargeslip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.chargeslip', verbose_name='Charge Slip'),
        ),
    ]
