# Generated by Django 4.0.6 on 2022-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0011_labhistory_code_servicehistory_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='servicecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
