# Generated by Django 4.0.6 on 2022-07-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0012_serviceinvoice_servicecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeslip',
            name='date_of_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete'),
        ),
        migrations.AddField(
            model_name='chargeslip',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargeslip',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='date_of_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete'),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='date_of_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_of_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
    ]
