# Generated by Django 4.0.6 on 2022-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0013_chargeslip_date_of_delete_chargeslip_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
