# Generated by Django 4.0.5 on 2022-07-21 19:33

from django.db import migrations, models
import vet.models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0014_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=vet.models.image_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=vet.models.image_path),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=vet.models.image_path),
        ),
    ]
