# Generated by Django 4.0.5 on 2022-07-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0015_pets_user_image_profile_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian')),
            ],
            options={
                'verbose_name_plural': 'Schedule Slot',
            },
        ),
        migrations.CreateModel(
            name='scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('arrived', models.BooleanField(default=False)),
                ('did_not_arrived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.pets', verbose_name='Pet')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.schedule_slot', verbose_name='Schedule')),
            ],
            options={
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
