# Generated by Django 3.2 on 2022-07-23 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0016_schedule_slot_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactNum',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be entered in format: 09XXXXXXXXX', regex='^09\\d{9}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='contactNum',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be entered in format: 09XXXXXXXXX', regex='^09\\d{9}$')], verbose_name='Contact Number'),
        ),
    ]
