# Generated by Django 4.0.6 on 2022-07-24 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0017_auto_20220723_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_slot',
            name='timeIn',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='schedule_slot',
            name='timeOut',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='schedule_slot',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.staffprofile', verbose_name='Veterinarian'),
        ),
    ]
