# Generated by Django 4.0.6 on 2022-07-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0018_alter_schedule_slot_timein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
