# Generated by Django 4.0.6 on 2022-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0019_scheduling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='date_of_cancelled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Delete'),
        ),
    ]
