# Generated by Django 4.0.5 on 2022-07-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0020_scheduling_date_of_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='flagsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagpoints', models.IntegerField(default='0', null=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('petOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.profile', verbose_name='Pet Owner')),
            ],
            options={
                'verbose_name_plural': 'Restriction for Scheduling',
            },
        ),
    ]
