# Generated by Django 4.0.6 on 2022-07-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0021_flagsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinvoice',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='chargeslip',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
