# Generated by Django 4.0.5 on 2022-07-27 18:41

from django.db import migrations, models
import vet.models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0023_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='user_image',
        ),
        migrations.AddField(
            model_name='pets',
            name='pet_image',
            field=models.ImageField(default='pet_img/pet_img.png', upload_to=vet.models.pet_image_path),
        ),
    ]
