# Generated by Django 4.0.5 on 2022-08-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0024_remove_pets_user_image_pets_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
