# Generated by Django 4.0.5 on 2022-08-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0025_scheduling_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='arrived',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='did_not_arrived',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='received',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
