# Generated by Django 4.0.5 on 2022-08-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0026_remove_scheduling_arrived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(blank=True, default='Reserved', max_length=200, null=True),
        ),
    ]
