# Generated by Django 4.0.5 on 2022-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0027_alter_scheduling_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
